const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src', 'pages', 'UploadNews.jsx');
let content = fs.readFileSync(filePath, 'utf8');

const translations = {
  "गलत पासवर्ड": "Incorrect password",
  "कृपया सही एडमिन पासवर्ड दर्ज करें।": "Please enter the correct admin password.",
  "राजनीति": "Politics",
  "व्यापार": "Business",
  "खेल": "Sports",
  "तकनीक": "Technology",
  "विज्ञान": "Science",
  "मनोरंजन": "Entertainment",
  "स्वास्थ्य": "Health",
  "विश्व समाचार": "World News",
  "देश": "National",
  "प्रदेश": "State",
  "पर्यावरण": "Environment",
  "अन्य": "Other",
  "काला": "Black",
  "सफ़ेद": "White",
  "ग्रे": "Gray",
  "लाल": "Red",
  "नीला": "Blue",
  "हरा": "Green",
  "नारंगी": "Orange",
  "पीला": "Yellow",
  "गुलाबी": "Pink",
  "बैंगनी": "Purple",
  "टीयल": "Teal",
  "कोई नहीं": "None",
  "कॉन्फ़िगरेशन सेटिंग्स सुरक्षित कर ली गई हैं": "Configuration settings saved successfully",
  "कृपया लिंक URL दर्ज करें:": "Please enter link URL:",
  "इमेजकिट क्रेडेंशियल्स (Public Key, URL Endpoint, Auth Endpoint) खाली हैं": "ImageKit credentials (Public Key, URL Endpoint, Auth Endpoint) are empty",
  "कृपया नीचे": "Please",
  "सेटिंग्स": "settings",
  "में जाकर इन्हें भरें ताकि फाइल सीधे ImageKit पर अपलोड हो सके।": "go below and fill them so the file can be uploaded directly to ImageKit.",
  "अपलोड करने में त्रुटि हुई। कृपया सेटिंग्स जांचें।": "Error during upload. Please check settings.",
  "कृपया खबर का शीर्षक दर्ज करें": "Please enter the news title",
  "जनवरी": "January",
  "फरवरी": "February",
  "मार्च": "March",
  "अप्रैल": "April",
  "मई": "May",
  "जून": "June",
  "जुलाई": "July",
  "अगस्त": "August",
  "सितंबर": "September",
  "अक्टूबर": "October",
  "नवंबर": "November",
  "दिसंबर": "December",
  "डेटाबेस सर्वर से कनेक्ट करने में विफल। क्या आपका नोड सर्वर चालू है": "Failed to connect to the database server. Is your node server running",
  "कृपया खबर को पहले डेटाबेस में सेव (Draft) करें": "Please save the news as a Draft in the database first",
  "ड्राफ्ट को सफलतापूर्वक वेबसाइट पर लाइव पब्लिश कर दिया गया है": "Draft has been successfully published live on the website",
  "बधाई हो": "Congratulations",
  "आपकी खबर डेटाबेस से वेबसाइट पर लाइव पब्लिश हो चुकी है।": "Your news has been published live from the database to the website.",
  "पब्लिश करने में त्रुटि हुई। कृपया सर्वर लॉग्स जांचें।": "Error during publishing. Please check server logs.",
  "ड्राफ्ट को फॉर्म एडिटर में लोड कर दिया गया है। आप बदलाव करके दोबारा सेव या पब्लिश कर सकते हैं": "Draft loaded into the form editor. You can make changes and save or publish again",
  "प्रशासक लॉगिन (Admin Login)": "Admin Login",
  "खबर अपलोड करने के लिए कृपया एडमिन पासवर्ड दर्ज करें।": "Please enter the admin password to upload news.",
  "पासवर्ड (Password)": "Password",
  "एडमिन पासवर्ड दर्ज करें": "Enter admin password",
  "वापस होमपेज": "Back to Homepage",
  "लॉगिन करें": "Login",
  "प्रकाशन स्थिति (Status):": "Publication Status:",
  "असुरक्षित (Not Saved)": "Not Saved",
  "डेटाबेस ड्राफ्ट (Draft)": "Database Draft",
  "लाइव पब्लिश (Live)": "Live Published",
  "एडिट करें": "Edit",
  "लाइव प्रीव्यू देखें": "View Live Preview",
  "सेव हो रहा है...": "Saving...",
  "पब्लिश हो रहा है...": "Publishing...",
  "त्रुटि (Database Error):": "Error (Database Error):",
  "यदि आपके पास बैकएंड सर्वर रनिंग नहीं है, तो कृपया नीचे दिए गए": "If you don't have a backend server running, please go to the",
  "कॉन्फ़िगरेशन": "Configuration",
  "सेटिंग्स में जाकर **Simulation Mode** चालू करें ताकि आप बिना एरर के परीक्षण कर सकें।": "settings below and enable **Simulation Mode** so you can test without errors.",
  "बिना शीर्षक की खबर": "Untitled News",
  "लेखक:": "Author:",
  "दिनांक: आज": "Date: Today",
  "खबर का संक्षिप्त विवरण यहाँ दिखाई देगा...": "News description will appear here...",
  "यहाँ खबर का विस्तृत लेख दिखाई देगा।": "Detailed news article will appear here.",
  "बुनियादी जानकारी": "Basic Information",
  "संपादन मोड:": "Edit Mode:",
  "शीर्षक (Title)": "Title",
  "विवरण (Description)": "Description",
  "खबर का मुख्य शीर्षक (Title)": "Main News Title",
  "खबर का मुख्य शीर्षक (Title) दर्ज करें": "Enter main news title",
  "उदा. विशेष रिपोर्टर, Editor": "e.g., Special Reporter, Editor",
  "अन्य,": "Other,",
  "संपादन मोड: मुख्य लेख": "Edit Mode: Main Article",
  "लिंक (Link)": "Link",
  "डबल कोट्स (Quotes)": "Double Quotes",
  "अक्षर का रंग (Text Color)": "Text Color",
  "रंग": "Color",
  "हाइलाइटर रंग (Highlight/Background Color)": "Highlight/Background Color",
  "हाइलाइट": "Highlight",
  "सामान्य पैराग्राफ": "Normal Paragraph",
  "मुख्य शीर्षक (H1)": "Main Heading (H1)",
  "उप": "Sub",
  "शीर्षक (H2)": "Heading (H2)",
  "छोटा हेडर (H3)": "Small Header (H3)",
  "ब्लॉककोट": "Blockquote",
  "यहाँ मुख्य खबर का विस्तारपूर्वक विवरण टाइप करें...": "Type the detailed description of the main news here...",
  "मीडिया फ़ाइल (Image / Video)": "Media File (Image / Video)",
  "इमेज खबर": "Image News",
  "वीडियो खबर": "Video News",
  "अपलोड की जा रही है...": "Uploading...",
  "फ़ाइल चुनें (": "Choose File (",
  "वीडियो": "Video",
  "इमेज": "Image",
  "के ज़रिए अपलोड करें": "Upload via",
  "अपलोड हुआ": "Uploaded",
  "फ़ाइल": "File",
  "सफलतापूर्वक सिमुलेट": "Simulated Successfully",
  "सफलतापूर्वक ImageKit पर": "Successfully on ImageKit",
  "अपलोड हो गई है": "Uploaded",
  "यहाँ इमेज/वीडियो का डायरेक्ट यूआरएल दिखेगा": "Direct URL of image/video will appear here",
  "उदा. https://www.youtube.com/watch": "e.g. https://www.youtube.com/watch",
  "अप्रकाशित समाचार ड्राफ्ट्स (Unpublished News Drafts)": "Unpublished News Drafts",
  "नीचे उन सभी खबरों की सूची है जो डेटाबेस में सेव हैं पर अभी तक लाइव पब्लिश नहीं हुई हैं।": "Below is the list of all news saved in the database but not yet published live.",
  "लिस्ट रीफ्रेश करें": "Refresh List",
  "त्रुटि (Draft Fetch Error):": "Error (Draft Fetch Error):",
  "यदि आपने अभी तक अपने नोड एक्सप्रेस बैकएंड में": "If you have not yet added the",
  "एंडपॉइंट नहीं जोड़ा है, तो कृपया": "endpoint in your node express backend, please add the code provided in",
  "में दिए गए कोड को राउटर फ़ाइल में जोड़ें और सर्वर रीस्टार्ट करें।": "to the router file and restart the server.",
  "ड्राफ्ट लोडिंग हो रहे हैं...": "Loading drafts...",
  "कोई अप्रकाशित ड्राफ्ट नहीं मिला": "No unpublished drafts found",
  "सभी खबरें लाइव पब्लिश हैं या कोई ड्राफ्ट सेव नहीं है।": "All news are published live or no draft is saved.",
  "लाइव करें": "Make Live"
};

for (const [hi, en] of Object.entries(translations)) {
  content = content.split(hi).join(en);
}

fs.writeFileSync(filePath, content, 'utf8');
console.log("Full translation complete!");
